### PR TITLE
feat: trigger release pipes from commit message

### PR DESCRIPTION
**Pull request by morrieinmaas**
Signed-off-by: Moriarty <moritz@animo.id>

### CODE REVIEW

**Comment by morrieinmaas** [comment]
@blu3beri haven't tested this yet but the idea is to be able to add:

```
[release:<aur|brew|choco>]
```
to the commit message to trigger the respective workflows to release based on latest tag for a platform (only).

**Comment by TimoGlastra** [comment]
Oh you are using workflow dispatch. nvm.

But where is the commit message for then?

**Comment by morrieinmaas** [comment]
> Oh you are using workflow dispatch. nvm.
> 
> But where is the commit message for then?

@TimoGlastra Thought it'd be handy to be able to put eg `[release:brew]` in the commit message to trigger it w/o having to use the GH website

**Comment by morrieinmaas** [comment]
but again not tested this yet - not sure this conflicts with the workflow dispatch

**Comment by morrieinmaas** [comment]
> Ah makes sense, but how I think it won't work like this. You should make a `push` trigger in that case that has the if statement. Because a workflow dispatch must be triggered from the UI if I remember correctly

Just pushed another commit that 'should' be what you're looking for/allows either

**Review by blu3beri — APPROVED** [review]
Looks good! However main is a protected branch. We have to create a pull request with no changes that contains a title 'release:brew', and merge it, right?

If it does not work, just using the manual dispatch is okay by me.

**Comment by morrieinmaas** [comment]
> Looks good! However main is a protected branch. We have to create a pull request with no changes that contains a title 'release:brew', and merge it, right?
> 
> If it does not work, just using the manual dispatch is okay by me.

Yes (ish) - haven't tested this so use with caution. If this doesn't work as expected I'll fix it.

**Comment by blu3beri** [comment]
I am fine with merging this and testing it. We can try to push directly to main with the commit msg, maybe empty commits are allowed, but if not we just use the workflow_dispatch. I dont think we should overengineer this and a simple button click is perfectly fine. This is a backupsystem after all.

**Pull request merged**
